
        TimerType* new TimerType(
        /* One-shot manual (time and channel based) */
            /* Type id. */
            TIMER_ONCE_MANUAL,
            /* Attributes. */
            TIMER_MANUAL_ATTRIBS,
            /* Description. */
            kodi::GetLocalizedString(MSG_ONETIME_MANUAL), // "One time (manual)",
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;

        /* One-shot epg based */
        TimerType* new TimerType(
            /* Type id. */
            TIMER_ONCE_EPG,
            /* Attributes. */
            TIMER_EPG_ATTRIBS,
            /* Description. */
            kodi::GetLocalizedString(MSG_ONETIME_GUIDE), // "One time (guide)",
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;


        /* Repeating manual (time and channel based) Parent */
        TimerType* new TimerType(
            /* Type id. */
            TIMER_REPEATING_MANUAL,
            /* Attributes. */
            TIMER_MANUAL_ATTRIBS | TIMER_REPEATING_MANUAL_ATTRIBS,
            /* Description. */
            kodi::GetLocalizedString(MSG_REPEATING_MANUAL), // "Repeating (manual)"
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;

        /* Repeating epg based Parent*/
        TimerType* new TimerType(
            /* Type id. */
            TIMER_REPEATING_EPG,
            /* Attributes. */
            TIMER_EPG_ATTRIBS | TIMER_REPEATING_EPG_ATTRIBS,
            /* Description. */
            kodi::GetLocalizedString(MSG_REPEATING_GUIDE), // "Repeating (guide)"
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;

        /* Read-only one-shot for timers generated by timerec */
        TimerType* new TimerType(
            /* Type id. */
            TIMER_ONCE_MANUAL_CHILD,
            /* Attributes. */
            TIMER_MANUAL_ATTRIBS | TIMER_CHILD_ATTRIBUTES,
            /* Description. */
            kodi::GetLocalizedString(MSG_REPEATING_CHILD), // "Created by Repeating Timer"
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;


        /* Read-only one-shot for timers generated by autorec */
        TimerType* new TimerType(
            /* Type id. */
            TIMER_ONCE_EPG_CHILD,
            /* Attributes. */
            TIMER_EPG_ATTRIBS | TIMER_CHILD_ATTRIBUTES,
            /* Description. */
            kodi::GetLocalizedString(MSG_REPEATING_CHILD), // "Created by Repeating Timer"
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;


        /* Repeating epg based Parent*/
        TimerType* new TimerType(
            /* Type id. */
            TIMER_REPEATING_KEYWORD,
            /* Attributes. */
            TIMER_KEYWORD_ATTRIBS | TIMER_REPEATING_KEYWORD_ATTRIBS,
            /* Description. */
            kodi::GetLocalizedString(MSG_REPEATING_KEYWORD), // "Repeating (keyword)"
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;


    types.emplace_back(
        /* Repeating epg based Parent*/
        new TimerType(
            /* Type id. */
            TIMER_REPEATING_ADVANCED,
            /* Attributes. */
            TIMER_ADVANCED_ATTRIBS | TIMER_REPEATING_KEYWORD_ATTRIBS,
            /* Description. */
            kodi::GetLocalizedString(MSG_REPEATING_ADVANCED), // "Repeating (advanced)"
            /* Values definitions for attributes. */
            recordingLimitValues, m_defaultLimit, showTypeValues, m_defaultShowType, recordingGroupValues, 0);
        types.emplace_back(*t);
        delete t;
